name:                tiny
version:             0.1.0.0
license:             BSD3
category:            Language

default-extensions:
- BangPatterns
- BlockArguments
- ConstraintKinds
- DeriveFunctor
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- ImplicitParams
- LambdaCase
- MultiParamTypeClasses
- NoMonomorphismRestriction
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- Strict
- TupleSections
- ViewPatterns

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-missing-signatures
- -Wno-unused-do-bind
- -Wno-unused-matches

source-dirs: .

executable:
  main: Main.hs
  dependencies:
    - base >= 4.7 && < 5
    - megaparsec
